# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  # setup_desktop:
  #   docker:
  #     - image: circleci/desktop:ubuntu-20.04
  #   steps:
  #     # Pasos para la configuración de desktop, si es necesario
  #     - checkout


  build:
    docker:
      - image: cimg/openjdk:19.0


    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Paso para clonar el repositorio
      - checkout

      # Paso para instalar IntelliJ IDEA y ejecutar el proyecto
      - run:
          name: Run IntelliJ IDEA build
          command: |
            # Descargar e instalar IntelliJ IDEA (reemplaza la URL con la versión que necesites)
            curl -L -o intellij.tar.gz https://download.jetbrains.com/idea/ideaIC-2021.3.1.tar.gz
            tar -zxvf intellij.tar.gz

            current_dir=$(pwd)
            cd idea*/bin
            ./idea.sh -Djava.awt.headless=true $current_dir compile


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  buildProject: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build